import Background from "./jungle-mountains.jpg"
import Background1 from "./blue-lake.jpg";
import Background2 from "./orange.jpg";
import GithubLogo from "./GH-Logo.png"
import Palette from "./palette512.png"
export { Background };
export { Background1 };
export { Background2 };
export { GithubLogo };
export { Palette };